import Image from "next/image";

export default function Home() {
  return (
    <main className="bg-white text-black dark:text-white dark:bg-black">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget ullamcorper turpis, a venenatis felis. Donec in venenatis sapien. Ut volutpat purus at metus maximus, nec egestas eros finibus. Nam lacinia risus a nibh convallis, quis pharetra mi fringilla. Aliquam erat volutpat. Integer sit amet fringilla felis. Cras elementum posuere turpis sit amet consectetur. Ut dictum augue purus, at condimentum turpis euismod quis. Suspendisse sollicitudin fermentum erat, a tristique dolor laoreet at. Proin aliquam orci sed urna consectetur, et scelerisque risus interdum. Curabitur lacinia nisl euismod nulla venenatis, id pharetra enim fringilla. Praesent a orci lorem. Mauris vitae diam quis mi volutpat fringilla sit amet ac nisl. Proin imperdiet metus felis. Vivamus et turpis non risus dapibus lobortis.

      Morbi scelerisque aliquet gravida. Etiam auctor quam ut egestas feugiat. Proin dapibus orci quis mauris auctor scelerisque. Nulla ac justo tempor, volutpat felis in, egestas mi. Mauris gravida eros risus, nec vestibulum enim malesuada non. Phasellus vel est non ante sollicitudin laoreet. Nulla facilisi. Suspendisse potenti. Nam ac velit metus. Donec id nisi felis. Suspendisse potenti. Mauris sit amet sapien malesuada, porttitor erat nec, eleifend odio. Ut cursus ipsum eros, nec sollicitudin metus ullamcorper vitae.

      Mauris vel venenatis lorem. Suspendisse sodales auctor elit eget sagittis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris a venenatis eros. Curabitur non venenatis ligula. Cras sit amet sapien felis. In nec felis nec sem convallis dictum ut sed turpis. Nulla efficitur, eros eu tincidunt tincidunt, purus erat iaculis orci, vitae gravida velit libero ac nulla. Aenean gravida cursus odio, nec interdum velit gravida et. Vivamus dictum tellus sed volutpat congue. Suspendisse eget erat id elit ornare posuere. Nunc porta ipsum eu lacus sodales posuere. Praesent vitae nisl id est laoreet cursus sed eu libero. Nulla id egestas magna. In vitae eros ante.

      Aenean convallis nulla et dolor scelerisque suscipit. Curabitur tincidunt purus risus, nec tincidunt neque elementum nec. Donec ac gravida nibh. Mauris pretium, est quis suscipit convallis, justo lacus bibendum nisi, ac faucibus ipsum nisi nec libero. Phasellus eget sollicitudin libero. Nam fermentum, nisi non feugiat gravida, arcu elit pellentesque orci, a rhoncus est augue non purus. Sed eleifend urna sapien, vitae feugiat nunc varius eu. Nam viverra interdum tortor, ut volutpat tortor sodales nec. Curabitur fermentum faucibus nulla, eget pretium eros ultrices ut. In efficitur feugiat fermentum.

      Vivamus facilisis justo ut dolor fermentum, nec vehicula risus rutrum. Proin sed nisl in nulla vehicula sagittis. Curabitur malesuada massa nulla, a scelerisque sapien fermentum non. Morbi vitae turpis non metus dictum posuere. Integer congue arcu ut orci rutrum tristique. Aenean pharetra libero ut erat aliquet, non congue lacus accumsan. Aliquam bibendum ligula quis leo faucibus finibus. Curabitur bibendum eros in nisi efficitur, eget ultrices metus consectetur. Ut malesuada mauris id tellus dictum, sed sollicitudin leo egestas. Fusce mollis leo at nisl efficitur, ut cursus odio euismod. Praesent at sapien quis risus aliquam feugiat vel sed tortor. Donec sagittis nulla at sodales finibus. Mauris dictum tempor ligula, nec sollicitudin augue gravida eget.
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget ullamcorper turpis, a venenatis felis. Donec in venenatis sapien. Ut volutpat purus at metus maximus, nec egestas eros finibus. Nam lacinia risus a nibh convallis, quis pharetra mi fringilla. Aliquam erat volutpat. Integer sit amet fringilla felis. Cras elementum posuere turpis sit amet consectetur. Ut dictum augue purus, at condimentum turpis euismod quis. Suspendisse sollicitudin fermentum erat, a tristique dolor laoreet at. Proin aliquam orci sed urna consectetur, et scelerisque risus interdum. Curabitur lacinia nisl euismod nulla venenatis, id pharetra enim fringilla. Praesent a orci lorem. Mauris vitae diam quis mi volutpat fringilla sit amet ac nisl. Proin imperdiet metus felis. Vivamus et turpis non risus dapibus lobortis.

      Morbi scelerisque aliquet gravida. Etiam auctor quam ut egestas feugiat. Proin dapibus orci quis mauris auctor scelerisque. Nulla ac justo tempor, volutpat felis in, egestas mi. Mauris gravida eros risus, nec vestibulum enim malesuada non. Phasellus vel est non ante sollicitudin laoreet. Nulla facilisi. Suspendisse potenti. Nam ac velit metus. Donec id nisi felis. Suspendisse potenti. Mauris sit amet sapien malesuada, porttitor erat nec, eleifend odio. Ut cursus ipsum eros, nec sollicitudin metus ullamcorper vitae.

      Mauris vel venenatis lorem. Suspendisse sodales auctor elit eget sagittis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris a venenatis eros. Curabitur non venenatis ligula. Cras sit amet sapien felis. In nec felis nec sem convallis dictum ut sed turpis. Nulla efficitur, eros eu tincidunt tincidunt, purus erat iaculis orci, vitae gravida velit libero ac nulla. Aenean gravida cursus odio, nec interdum velit gravida et. Vivamus dictum tellus sed volutpat congue. Suspendisse eget erat id elit ornare posuere. Nunc porta ipsum eu lacus sodales posuere. Praesent vitae nisl id est laoreet cursus sed eu libero. Nulla id egestas magna. In vitae eros ante.

      Aenean convallis nulla et dolor scelerisque suscipit. Curabitur tincidunt purus risus, nec tincidunt neque elementum nec. Donec ac gravida nibh. Mauris pretium, est quis suscipit convallis, justo lacus bibendum nisi, ac faucibus ipsum nisi nec libero. Phasellus eget sollicitudin libero. Nam fermentum, nisi non feugiat gravida, arcu elit pellentesque orci, a rhoncus est augue non purus. Sed eleifend urna sapien, vitae feugiat nunc varius eu. Nam viverra interdum tortor, ut volutpat tortor sodales nec. Curabitur fermentum faucibus nulla, eget pretium eros ultrices ut. In efficitur feugiat fermentum.

      Vivamus facilisis justo ut dolor fermentum, nec vehicula risus rutrum. Proin sed nisl in nulla vehicula sagittis. Curabitur malesuada massa nulla, a scelerisque sapien fermentum non. Morbi vitae turpis non metus dictum posuere. Integer congue arcu ut orci rutrum tristique. Aenean pharetra libero ut erat aliquet, non congue lacus accumsan. Aliquam bibendum ligula quis leo faucibus finibus. Curabitur bibendum eros in nisi efficitur, eget ultrices metus consectetur. Ut malesuada mauris id tellus dictum, sed sollicitudin leo egestas. Fusce mollis leo at nisl efficitur, ut cursus odio euismod. Praesent at sapien quis risus aliquam feugiat vel sed tortor. Donec sagittis nulla at sodales finibus. Mauris dictum tempor ligula, nec sollicitudin augue gravida eget.
    </main>
  );
}
